apiVersion: v1
kind: Pod
metadata:
  labels:
    run: xrserver
  name: xrserver
spec:
  containers:
  - image: ghcr.io/xregistry/xrserver
    imagePullPolicy: Never
    name: xrserver
    command: [ "/xrserver" ]
    args: [ "--recreate" ]
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: DBHOST
      value: mysql
    - name: DBPORT
      value: "3306"

---

apiVersion: v1
kind: Service
metadata:
  name: xrserver
spec:
  ports:
  - nodePort: 32000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: xrserver
  sessionAffinity: None
  type: NodePort

