name: CI
on:
  push:
    branches:
      - master

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set IMAGE env var to use the github org name
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY%/*}/xreg-server" >> $GITHUB_ENV

      - name: Show env vars for debugging
        run: env | sort

      - name: ghcr.io login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build, test, push
        run: make mysql test push

      - env:
          SOAPHUB_SSH_KEY: ${{ secrets.SOAPHUB_SSH_KEY }}
        run: misc/restart SOAPHUB_SSH_KEY ubuntu@soaphub.org

