name: PR-CI
on:
  pull_request:
    branches-ignore:
      - master

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show env vars for debugging
        run: env | sort

      - name: build, test
        run: make mysql test

